services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    restart: unless-stopped
    # Custom volume for data persistence
    volumes:
      - metabase-data:/metabase-data
volumes:
  metabase-data:
